-- Source presentation and administration fields.  Source contracts remain a
-- separate review gate: registering a source never activates a collector.
ALTER TABLE sources
  ADD COLUMN display_name VARCHAR(255),
  ADD COLUMN homepage_url VARCHAR(2000),
  ADD COLUMN logo_url VARCHAR(2000),
  ADD COLUMN content_area VARCHAR(30) NOT NULL DEFAULT 'GENERAL'
    CHECK (content_area IN ('CATALOG','RESEARCH','INSIGHTS','SAFETY','SOFTWARE','IMAGES','INTEGRATORS','MARKET','GENERAL')),
  ADD COLUMN admin_description TEXT,
  ADD COLUMN public_description TEXT,
  ADD COLUMN is_public BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX idx_sources_area_public ON sources(content_area, is_public);

-- Registry seed from robotspace/SOURCE-AUDIT-2026-07-23.md.  All entries are
-- intentionally PROPOSED: an agent may use one only after its contract,
-- current terms and rate policy have been reviewed.
INSERT INTO sources (
  key, display_name, owner_name, homepage_url, content_area, admin_description, public_description,
  is_public, tier, source_type, status, legal_status, rate_limit_rpm, trust_default_confidence, kill_switch
) VALUES
('wikidata', 'Wikidata', 'Wikimedia Foundation', 'https://www.wikidata.org/wiki/Wikidata:Data_access', 'CATALOG',
 'Discovery and entity resolution: QIDs, labels, aliases, manufacturer, country and official links. CC0, but use a descriptive User-Agent and backoff. Never treat it as the primary technical-specification source.',
 'Open structured data used to identify robotics companies and products, then verified against stronger evidence.', true, 'B', 'SPARQL', 'PROPOSED', 'ALLOWED', 10, 0.65, false),
('wikimedia-commons', 'Wikimedia Commons', 'Wikimedia Foundation', 'https://commons.wikimedia.org/wiki/Commons:Reusing_content_outside_Wikimedia', 'IMAGES',
 'Open image candidate. Record license, author, credit and landing page per file; trademark and privacy restrictions can still apply.',
 'Open-media discovery with per-file license and attribution checks.', true, 'B', 'API', 'PROPOSED', 'ALLOWED', 10, 0.80, false),
('robots-ros', 'robots.ros.org', 'Open Robotics / ROS community', 'https://robots.ros.org/', 'SOFTWARE',
 'ROS robot identity, tags, descriptions and ROS links. CC BY 3.0 except where stated; useful for identity and compatibility, not price or commercial availability.',
 'ROS ecosystem references used to confirm robot identity and software context.', true, 'B', 'HTML', 'PROPOSED', 'ALLOWED', 10, 0.80, false),
('rosdistro', 'rosdistro', 'Open Robotics / ROS community', 'https://github.com/ros/rosdistro', 'SOFTWARE',
 'Official ROS distribution repository for packages, distributions and versions. Package presence alone does not prove physical robot compatibility.',
 'Official ROS distribution metadata for software versions and packages.', true, 'A', 'FILE_FEED', 'PROPOSED', 'ALLOWED', 10, 0.85, false),
('arxiv', 'arXiv', 'Cornell University', 'https://info.arxiv.org/help/api/tou.html', 'RESEARCH',
 'Research stream for title, abstract metadata, authors, categories, DOI and dates. Use at most one request per three seconds and do not republish PDFs without checking rights.',
 'Research metadata for robotics papers, with links to the original work.', true, 'A', 'API', 'PROPOSED', 'ALLOWED', 20, 0.93, false),
('openalex', 'OpenAlex', 'OpenAlex', 'https://developers.openalex.org/api-reference/authentication', 'RESEARCH',
 'Research enrichment for works, institutions, topics and citations. Requires API key/budget monitoring; full-text rights remain separate.',
 'Research discovery and citation metadata, subject to source licensing.', true, 'B', 'API', 'PROPOSED', 'UNKNOWN', 10, 0.93, false),
('crossref', 'Crossref', 'Crossref', 'https://www.crossref.org/documentation/retrieve-metadata/rest-api/', 'RESEARCH',
 'DOI identity verification and normalization. Read dynamic rate-limit headers; abstracts can be copyrighted.',
 'DOI and publication metadata used to verify research references.', true, 'A', 'API', 'PROPOSED', 'ALLOWED', 3, 0.97, false),
('the-robot-report', 'The Robot Report', 'WTWH Media', 'https://www.therobotreport.com/feed/', 'INSIGHTS',
 'News discovery via RSS. Store only metadata and original short preview; discard feed HTML and link to the publisher.',
 'Robotics-news metadata and links to original reporting.', true, 'C', 'RSS', 'PROPOSED', 'RESTRICTED_RISK', 10, 0.85, true),
('ieee-spectrum-robotics', 'IEEE Spectrum Robotics', 'IEEE', 'https://spectrum.ieee.org/feeds/topic/robotics.rss', 'INSIGHTS',
 'News discovery via RSS. Descriptions can contain near-full articles, so store metadata only and never persist protected feed HTML.',
 'Robotics-news metadata and links to original IEEE Spectrum coverage.', true, 'C', 'RSS', 'PROPOSED', 'RESTRICTED_RISK', 10, 0.85, true),
('eu-safety-gate', 'EU Safety Gate', 'European Commission', 'https://data.europa.eu/data/datasets/rapex-rapid-alert-system-non-food?locale=en', 'SAFETY',
 'EU product safety notices: model, country, risk, measure and date. Preserve attribution; image rights are separate. This is a recall relation, not a product safety rating.',
 'European product-safety and recall notices where relevant.', true, 'A', 'API', 'PROPOSED', 'ALLOWED', 10, 0.97, false),
('cpsc-recalls', 'CPSC Recalls API', 'U.S. Consumer Product Safety Commission', 'https://www.cpsc.gov/Recalls/CPSC-Recalls-Application-Program-Interface-API-Information', 'SAFETY',
 'US consumer recall API for recall ID, product/model, brand, hazard, remedy and dates. Image and trademark rights are separate.',
 'United States consumer product-recall metadata.', true, 'A', 'API', 'PROPOSED', 'ALLOWED', 10, 0.97, false),
('openfda-devices', 'openFDA Device APIs', 'U.S. Food and Drug Administration', 'https://open.fda.gov/apis/device/', 'SAFETY',
 'Medical-device-only identity, distribution and recall/adverse-event records. Requires API key for regular load and is not medical advice.',
 'Public medical-device regulatory metadata for applicable robotics categories.', true, 'A', 'API', 'PROPOSED', 'ALLOWED', 10, 0.97, false),
('accessgudid', 'AccessGUDID', 'U.S. National Library of Medicine', 'https://accessgudid.nlm.nih.gov/resources/developers/device_lookup_api', 'SAFETY',
 'Medical device identity/status by UDI-DI, model and catalogue. Follow NLM and API policies.',
 'Medical-device identification and status data where applicable.', true, 'A', 'API', 'PROPOSED', 'ALLOWED', 10, 0.97, false),
('gazebo-fuel', 'Gazebo Fuel', 'Open Robotics', 'https://gazebosim.org/libs/fuel_tools/', 'SOFTWARE',
 'Simulation assets, SDF, owner, tags, versions and per-item license. Simulation availability does not prove physical support.',
 'Simulation-model discovery with per-asset license checks.', true, 'B', 'API', 'PROPOSED', 'UNKNOWN', 10, 0.80, false),
('vda-5050', 'VDA 5050', 'VDA', 'https://github.com/VDA5050/VDA5050', 'SOFTWARE',
 'AMR interoperability schemas and versions. A standard does not prove that a particular robot supports it without vendor evidence.',
 'AMR interoperability standard references and version metadata.', true, 'A', 'FILE_FEED', 'PROPOSED', 'ALLOWED', 10, 0.90, false),
('opc-ua-robotics', 'OPC UA Robotics', 'OPC Foundation', 'https://reference.opcfoundation.org/Robotics/v102/docs/', 'SOFTWARE',
 'Industrial robotics information-model reference. It is a standard reference, not a product compatibility feed.',
 'Industrial robotics interoperability reference material.', true, 'A', 'HTML', 'PROPOSED', 'UNKNOWN', 10, 0.90, false),
('odva-marketplace', 'ODVA Marketplace', 'ODVA', 'https://marketplace.odva.org/products/', 'SOFTWARE',
 'Discovery for product and conformance listings. Bulk API and reuse permission are not confirmed.',
 'Industrial-network product discovery, pending permission review.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.70, true),
('pi-product-finder', 'PI Product Finder', 'PROFIBUS & PROFINET International', 'https://productfinder.profinet.com/', 'SOFTWARE',
 'PROFINET product/certificate discovery. Bulk access permission must be confirmed before collection.',
 'PROFINET product and certificate discovery, pending permission review.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.70, true),
('abb-customer-stories', 'ABB Customer Stories', 'ABB', 'https://www.abb.com/global/en/areas/robotics/news-and-media/customer-stories', 'MARKET',
 'Deployment and application discovery. Treat as marketing/self-reported; store facts and an original rewrite with a link only.',
 'Manufacturer case-study links for deployment research.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.60, true),
('kuka-case-studies', 'KUKA Case Studies', 'KUKA', 'https://www.kuka.com/en-us/industries/solutions-database/', 'MARKET',
 'Deployment and industry discovery. Marketing/self-reported with commercial reuse restrictions.',
 'Manufacturer case-study links for deployment research.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.60, true),
('ur-resource-hub', 'Universal Robots Resource Hub', 'Universal Robots', 'https://www.universal-robots.com/resources/?filters=content_type%3Acase_story', 'MARKET',
 'Application and case-story discovery. Follow the manufacturer content and reuse rules; retain facts plus original rewrite only.',
 'Manufacturer resource links for application research.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.60, true),
('csia-directory', 'CSIA Integrator Directory', 'Control System Integrators Association', 'https://controlsys.org/find-an-integrator/', 'INTEGRATORS',
 'Integrator discovery and specialties. No feed/reuse permission is confirmed, so do not bulk collect.',
 'Integrator discovery reference, pending permission review.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.60, true),
('automate-exhibitors', 'Automate Exhibitors', 'Association for Advancing Automation', 'https://www.automateshow.com/exhibitors', 'INTEGRATORS',
 'Event exhibitor discovery. Listings are year-specific and self-reported; no bulk license is confirmed.',
 'Event exhibitor discovery reference, pending permission review.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.60, true),
('irex-exhibitors', 'iREX Exhibitors', 'Japan Robot Association / Nikkan Kogyo Shimbun', 'https://irex.nikkan.co.jp/exhibitor', 'INTEGRATORS',
 'Japan/Asia event exhibitor discovery. Self-reported and subject to directory reuse restrictions.',
 'Japan and Asia exhibitor discovery reference, pending permission review.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.60, true),
('automatica-exhibitors', 'automatica Exhibitors', 'Messe München', 'https://automatica-munich.com/en/trade-fair/exhibitors/overview/', 'INTEGRATORS',
 'European event exhibitor discovery. Self-reported and subject to directory reuse restrictions.',
 'European exhibitor discovery reference, pending permission review.', false, 'C', 'HTML', 'PROPOSED', 'RESTRICTED_RISK', 5, 0.60, true),
('nvd-cve', 'NVD CVE API', 'National Institute of Standards and Technology', 'https://nvd.nist.gov/developers/vulnerabilities', 'SAFETY',
 'Security vulnerability and CPE relations. Product/version matching is difficult and must not be inferred automatically.',
 'Public cybersecurity-vulnerability metadata for verified product/version links.', true, 'A', 'API', 'PROPOSED', 'ALLOWED', 10, 0.90, false),
('nvidia-isaac-ros', 'NVIDIA Isaac ROS Supported Robots', 'NVIDIA', 'https://nvidia-isaac-ros.github.io/robots/index.html', 'SOFTWARE',
 'Official but narrow robot-support evidence for Isaac ROS. Do not generalize it to overall ROS support.',
 'Official Isaac ROS compatibility references for their documented scope.', true, 'B', 'HTML', 'PROPOSED', 'UNKNOWN', 10, 0.80, false),
('openverse', 'Openverse API', 'WordPress Foundation', 'https://api.openverse.org/', 'IMAGES',
 'Image discovery with creator and license metadata. License accuracy is not guaranteed: verify the original landing page before use.',
 'Open-media discovery with independent license verification.', true, 'B', 'API', 'PROPOSED', 'ALLOWED', 10, 0.75, false)
ON CONFLICT (key) DO NOTHING;
