import Link from 'next/link'
import type { RobotEcosystem } from '../../../lib/robot-ecosystem'

const resourceLabels: Record<string, string> = { WEBSITE: 'Website', DOCS: 'Documentation', SDK: 'SDK', GITHUB: 'GitHub', ROS: 'ROS', ROS2: 'ROS 2', HUGGING_FACE: 'Hugging Face', FIRMWARE: 'Firmware' }
function shortDate(value: Date | null) { return value ? value.toISOString().slice(0, 10) : null }
function typeLabel(value: string) { return value.replaceAll('_', ' ').replace(/\b\w/g, letter => letter.toUpperCase()) }

function ProjectCards({ projects, official }: { projects: RobotEcosystem['officialProjects']; official: boolean }) {
  if (!projects.length) return <p className="mt-3 text-sm" style={{ color: 'var(--color-text-muted)' }}>{official ? 'No official software project has been verified yet.' : 'No verified community project has been linked yet.'}</p>
  return <div className="mt-4 grid md:grid-cols-2 gap-4">{projects.map(project => <article key={project.id} className="rounded-xl border p-5" style={{ borderColor: project.trustStatus === 'DISPUTED' ? 'var(--color-warning, #d9a441)' : official ? 'var(--color-accent-data)' : 'var(--color-border-color)', background: 'var(--color-bg-card)' }}><div className="flex flex-wrap justify-between gap-2"><span className="text-xs uppercase tracking-wider" style={{ color: official ? 'var(--color-accent-data)' : 'var(--color-text-dim)' }}>{typeLabel(project.originStatus)}</span><span className="rounded-full border px-2 py-0.5 text-xs" style={{ borderColor: 'var(--color-border-color)' }}>{typeLabel(project.projectType)}</span></div><h3 className="mt-3 text-lg font-medium"><Link href={`/projects/${project.slug}`} className="hover:underline">{project.name}</Link></h3>{project.description && <p className="mt-2 text-sm line-clamp-3" style={{ color: 'var(--color-text-muted)' }}>{project.description}</p>}<div className="mt-4 flex flex-wrap gap-x-3 gap-y-1 text-xs" style={{ color: 'var(--color-text-dim)' }}><span>#{project.ranking.rank} of {project.ranking.total} in this robot ecosystem</span><span>{project.trustStatus === 'DISPUTED' ? 'Community reports conflict' : project.trustStatus === 'COMMUNITY_CONFIRMED' ? 'Community confirmed' : 'Editorially verified'}{project.verifiedAt ? ` ${shortDate(project.verifiedAt)}` : ''}</span><span>{project.confirmedCount} confirm · {project.disputedCount} dispute</span>{project.latestRelease && <span>Release {project.latestRelease}</span>}{project.githubCheckedAt && <span>GitHub checked {shortDate(project.githubCheckedAt)}</span>}{project.githubSyncStatus && project.githubSyncStatus !== 'OK' && <span>GitHub data temporarily unavailable; previous verified data is retained.</span>}</div><p className="mt-3 text-xs" style={{ color: 'var(--color-text-muted)' }}>Why this order: {project.ranking.reasons.join(' · ')}. Formula {project.ranking.formulaVersion}.</p><div className="mt-3 flex flex-wrap gap-3 text-xs"><Link href={`/compatibility/${project.compatibilityId}`} className="underline">Trust record</Link>{project.repositoryUrl && <a href={project.repositoryUrl} target="_blank" rel="noopener noreferrer" className="underline">Repository</a>}{project.evidence.map((source, index) => <a key={`${source.url}-${index}`} href={source.url} target="_blank" rel="noopener noreferrer" className="underline" style={{ color: 'var(--color-text-muted)' }}>Evidence {index + 1}</a>)}</div></article>)}</div>
}

export function RobotEcosystemSections({ ecosystem, robotSlug }: { ecosystem: RobotEcosystem; robotSlug: string }) {
  const hasEcosystem = ecosystem.resources.length + ecosystem.officialProjects.length + ecosystem.communityProjects.length > 0
  return <section id="ecosystem" className="py-8 space-y-8 border-t" style={{ borderColor: 'var(--color-border-color)' }} aria-labelledby="ecosystem-title">
    <div className="flex flex-wrap justify-between gap-5 items-end"><div><p className="text-xs uppercase tracking-[0.16em]" style={{ color: 'var(--color-accent-data)' }}>Verified ecosystem</p><h2 id="ecosystem-title" className="mt-1 text-2xl font-medium">Software and resources</h2><p className="mt-2 max-w-2xl text-sm" style={{ color: 'var(--color-text-muted)' }}>Official links and community projects are shown separately. Every published relationship has reviewable evidence.</p></div><div className="flex flex-wrap gap-2"><Link href="/projects/new" className="rounded-md border px-3 py-2 text-sm">Add project</Link><Link href={`/compatibility/new?robot=${encodeURIComponent(robotSlug)}`} className="rounded-md border px-3 py-2 text-sm">Confirm compatibility</Link><Link href={`/corrections/new?entity=${encodeURIComponent(robotSlug)}`} className="rounded-md border px-3 py-2 text-sm">Submit correction</Link></div></div>

    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3" aria-label="Ecosystem maturity indicators"><div className="rounded-xl border p-4"><div className="text-2xl font-semibold">{ecosystem.maturity.verifiedResourceCount}</div><div className="mt-1 text-xs" style={{ color: 'var(--color-text-muted)' }}>verified official resources</div></div><div className="rounded-xl border p-4"><div className="text-2xl font-semibold">{ecosystem.maturity.verifiedProjectCount}</div><div className="mt-1 text-xs" style={{ color: 'var(--color-text-muted)' }}>verified compatible projects</div></div><div className="rounded-xl border p-4"><div className="text-2xl font-semibold">{ecosystem.maturity.activeMaintainerCount}</div><div className="mt-1 text-xs" style={{ color: 'var(--color-text-muted)' }}>public maintainers</div></div><div className="rounded-xl border p-4"><div className="text-sm font-medium">{ecosystem.maturity.latestVerifiedActivity ? shortDate(ecosystem.maturity.latestVerifiedActivity) : 'No activity yet'}</div><div className="mt-1 text-xs" style={{ color: 'var(--color-text-muted)' }}>latest verified ecosystem activity</div></div></div>
    <p className="text-xs" style={{ color: 'var(--color-text-dim)' }}>Projects are ordered only within this robot ecosystem using verified compatibility, GitHub freshness and activity, and accepted community reports. This is not a global RobotSpace score.</p>

    <section aria-labelledby="official-resources"><h3 id="official-resources" className="text-xl font-medium">Official resources</h3>{ecosystem.resources.length ? <div className="mt-4 grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{ecosystem.resources.map(resource => <article key={resource.id} className="rounded-xl border p-4" style={{ borderColor: 'var(--color-accent-data)', background: 'var(--color-bg-card)' }}><div className="flex justify-between gap-2"><span className="text-xs uppercase tracking-wider" style={{ color: 'var(--color-accent-data)' }}>{resourceLabels[resource.resource_type] ?? typeLabel(resource.resource_type)}</span><span className="text-xs">Verified</span></div><a href={resource.url} target="_blank" rel="noopener noreferrer" className="mt-3 block font-medium hover:underline">{resource.title} ↗</a><div className="mt-3 flex flex-wrap gap-3 text-xs" style={{ color: 'var(--color-text-muted)' }}><span>Checked {shortDate(resource.verified_at)}</span><a href={resource.evidence_url} target="_blank" rel="noopener noreferrer" className="underline">Evidence</a></div></article>)}</div> : <p className="mt-3 text-sm" style={{ color: 'var(--color-text-muted)' }}>No first-party resource has been independently verified yet. Unverified catalog links are not shown as official.</p>}</section>

    <section aria-labelledby="official-projects"><h3 id="official-projects" className="text-xl font-medium">Official software</h3><ProjectCards projects={ecosystem.officialProjects} official /></section>
    <section aria-labelledby="community-projects"><h3 id="community-projects" className="text-xl font-medium">Community projects</h3><ProjectCards projects={ecosystem.communityProjects} official={false} /></section>

    <div className="grid lg:grid-cols-2 gap-5"><section className="rounded-xl border p-5" aria-labelledby="maintainers"><h3 id="maintainers" className="text-lg font-medium">Developers and contributors</h3>{ecosystem.contributors.length ? <ul className="mt-3 space-y-2">{ecosystem.contributors.map(person => <li key={person.handle} className="flex justify-between gap-3 text-sm"><Link href={`/developers/${person.handle}`} className="underline">{person.displayName ?? `@${person.handle}`}</Link><span style={{ color: 'var(--color-text-dim)' }}>{person.projectCount} project{person.projectCount === 1 ? '' : 's'}</span></li>)}</ul> : <p className="mt-3 text-sm" style={{ color: 'var(--color-text-muted)' }}>No public maintainer profile is linked yet.</p>}</section><section className="rounded-xl border p-5" aria-labelledby="activity"><h3 id="activity" className="text-lg font-medium">Verified activity</h3>{ecosystem.activity.length ? <ul className="mt-3 space-y-3">{ecosystem.activity.map(project => <li key={project.id} className="text-sm"><Link href={`/projects/${project.slug}`} className="font-medium hover:underline">{project.name}</Link><span className="block text-xs mt-1" style={{ color: 'var(--color-text-dim)' }}>{shortDate(project.lastActivityAt)} · {typeLabel(project.projectType)}{project.latestRelease ? ` · ${project.latestRelease}` : ''}</span></li>)}</ul> : <p className="mt-3 text-sm" style={{ color: 'var(--color-text-muted)' }}>No verified project activity is available.</p>}</section></div>

    {!hasEcosystem && <div className="rounded-xl border p-6 text-center"><h3 className="font-medium">This ecosystem is still empty</h3><p className="mt-2 text-sm" style={{ color: 'var(--color-text-muted)' }}>The robot page remains useful for specifications while official resources and compatible projects are being verified.</p></div>}
  </section>
}
