INSERT INTO sources (key,display_name,owner_name,homepage_url,content_area,admin_description,public_description,is_public,tier,source_type,status,legal_status,rate_limit_rpm,trust_default_confidence,kill_switch)
VALUES
('techxplore-robotics','Tech Xplore Robotics','Science X','https://techxplore.com/rss-feed/robotics-news/','INSIGHTS','RSS metadata only: title, date, categories and original URL. No article HTML, images or feed excerpts are retained.','Robotics news metadata and links to original reporting.',true,'B','RSS','ACTIVE','ALLOWED',2,.85,false),
('robotics-247','Robotics 247','Robotics 247','https://www.robotics247.com/rss','INSIGHTS','RSS metadata only: title, date, categories and original URL.','Robotics industry news metadata and links.',true,'B','RSS','ACTIVE','ALLOWED',2,.80,false),
('robotics-automation-news','Robotics and Automation News','Robotics and Automation News','https://roboticsandautomationnews.com/feed/','INSIGHTS','RSS metadata only: title, date, categories and original URL.','Robotics and automation news metadata and links.',true,'B','RSS','ACTIVE','ALLOWED',2,.80,false),
('robohub','RoboHub','RoboHub','https://robohub.org/feed/','INSIGHTS','RSS metadata only: title, date, categories and original URL.','Robotics research and community news metadata and links.',true,'B','RSS','ACTIVE','ALLOWED',2,.80,false),
('humanoid-guide-news','Humanoid Guide News','Humanoid.guide','https://humanoid.guide/feed/','INSIGHTS','RSS metadata only: title, date, categories and original URL.','Humanoid robotics news metadata and links.',true,'B','RSS','ACTIVE','ALLOWED',2,.85,false)
ON CONFLICT (key) DO NOTHING;

UPDATE sources SET status='ACTIVE',legal_status='ALLOWED',kill_switch=false,rate_limit_rpm=2,updated_at=now() WHERE key='the-robot-report';

INSERT INTO source_contracts (source_key,canonical_endpoint,access_mode,legal_basis,allowed_fields,allowed_operations,raw_retention_policy,publication_policy,rate_limit_strategy,stable_id_strategy,parser_version,schema_version)
SELECT key,homepage_url,'RSS_METADATA','Operator-approved RSS metadata discovery: retain title, date, categories and canonical URL only.','["title","published_at","categories","canonical_url"]','["metadata_discovery","deduplication"]','No raw RSS, HTML, images, excerpts or article bodies retained.','Only high-relevance July 2026+ metadata; link to original.','Maximum two requests per minute, one request per feed per run.','Canonical URL','rss-metadata-v1','1' FROM sources WHERE key IN ('techxplore-robotics','robotics-247','robotics-automation-news','robohub','humanoid-guide-news','the-robot-report') AND NOT EXISTS (SELECT 1 FROM source_contracts c WHERE c.source_key=sources.key);

UPDATE scheduled_agents SET implementation_status='READY',is_enabled=true,cron_expression='5 */6 * * *',source_keys='["techxplore-robotics","robotics-247","robotics-automation-news","robohub","humanoid-guide-news","the-robot-report"]'::jsonb,description='Collects July 2026+ robotics-news metadata from approved RSS feeds, filters for high relevance and deduplicates by canonical URL and similar title. It never stores article HTML or images.' WHERE agent_key='insights-metadata-collector';
