UPDATE robot_public_projections SET summary = 
  CASE canonical_name
    WHEN 'Atlas' THEN 'Bipedal humanoid platform developed for dynamic mobility and whole-body manipulation. The 28-degree-of-freedom system combines hydraulic actuation with onboard perception, enabling autonomous navigation across unstructured terrain. Atlas walks, runs, jumps and performs acrobatic maneuvers -- capabilities uncommon in hydraulic robots of its 89-kilogram weight class. Its 120 kg payload capacity and real-time environmental mapping make it suited for disaster response, construction logistics and defense applications. First demonstrated publicly in 2013, the platform has seen five major hardware revisions through 2025.'
    WHEN 'Spot' THEN 'Quadruped inspection robot designed for industrial monitoring and data collection in hazardous or hard-to-reach environments. The 12-degree-of-freedom chassis carries a 14 kg sensor payload across stairs, gravel and confined spaces at 1.6 meters per second. Spot navigates autonomously using stereo cameras and LiDAR, returning to its dock for charging between missions. Weighing 32 kg, it deploys from a vehicle or backpack and operates in rain, dust and temperatures from -20 C to 45 C. Deployed in power plants, construction sites, offshore platforms and public safety operations since 2020.'
    WHEN 'Stretch' THEN 'Mobile case-handling robot purpose-built for warehouse automation and trailer unloading. Stretch combines a 7-degree-of-freedom arm with 2100 mm reach and a compact omnidirectional base weighing just 24 kg. The vacuum gripper system handles boxes up to 23 kg at rates exceeding 800 cases per hour. Its vision system identifies cartons, totes and polybags without SKU pre-programming, adapting to mixed pallets in real time. Deployed in logistics centers from 2022, Stretch targets the labor-intensive unloading task that has resisted automation for decades.'
    WHEN 'UR5e' THEN 'Lightweight collaborative 6-axis robot arm engineered for small-part assembly, pick-and-place and machine tending alongside human operators. The UR5e achieves 850 mm reach with 5 kg payload capacity and 0.03 mm repeatability -- sufficient for electronics assembly, screwdriving and dispensing applications. At 18.4 kg, it mounts directly on workbenches without anchoring. Built-in force-torque sensing enables safe human-robot collaboration without external guarding. Universal Robots e-Series platform supports plug-and-play grippers, vision systems and force sensors through a single electrical interface.'
    WHEN 'UR10e' THEN 'Heavy-duty collaborative robot arm rated for 12.5 kg payload across 1300 mm reach. The 6-axis design provides 0.05 mm repeatability for palletizing, packaging, machine tending and welding operations in shared workspaces. At 33.5 kg, the UR10e combines collaborative safety with industrial throughput -- force-limiting technology eliminates the need for safety fencing in most applications while maintaining cycle times competitive with traditional industrial robots. Over 50 certified plug-and-play end effectors and accessories are available through the UR+ ecosystem.'
    WHEN 'UR20' THEN 'Next-generation collaborative robot with industry-leading 20 kg payload capacity in a 64 kg package. The UR20 extends reach to 1750 mm while maintaining 0.05 mm repeatability -- a combination that opens palletizing, heavy machine tending and welding applications previously requiring traditional industrial robots. All-new joint design delivers faster cycle times and smoother motion across the full 6-axis envelope. Backward-compatible with UR+ accessories, the UR20 reduces the cost barrier for high-payload collaborative automation.'
    WHEN 'KUKA KR 1000 titan' THEN 'Heavy-duty 6-axis industrial robot built for extreme payload applications in foundry, construction and heavy manufacturing. With 1000 kg payload capacity and 3200 mm reach, the KR 1000 titan handles large castings, concrete elements, stone blocks and steel structures. The 4700 kg robot provides 0.1 mm repeatability and full IP65/67 protection for harsh environments. KUKA motion control software optimizes path planning for the robot substantial inertia, minimizing cycle times in high-mass handling operations.'
    WHEN 'KUKA KR 6 R900' THEN 'Compact 6-axis industrial robot optimized for arc welding, adhesive dispensing and small-part handling. The KR 6 R900 delivers 6 kg payload, 900 mm reach and 0.03 mm repeatability in a 52 kg package -- suitable for cell-based production with minimal footprint. Hollow-wrist design simplifies weld torch cabling and reduces interference in tight spaces. Integrated energy supply through the arm eliminates external cable drag chains, improving reliability in continuous 3-shift operation.'
    WHEN 'ABB IRB 6700' THEN 'High-performance industrial robot series covering 150-300 kg payload range for spot welding, material handling and machining tending. The IRB 6700 reaches 3050 mm and weighs 1225 kg, delivering 0.05 mm repeatability with best-in-class path accuracy. ABB QuickMove and TrueMove motion control optimizes acceleration profiles for minimum cycle time without overshoot. LeanID integrated dress pack routes welding cables and hoses through the upper arm, reducing interference risk in multi-robot cells. Deployed across automotive body shops worldwide.'
    WHEN 'ABB IRB 1200' THEN 'Compact flexible industrial robot for small parts assembly, material handling and packaging in confined production cells. The IRB 1200 handles 7 kg payload at 900 mm reach with 0.025 mm repeatability. At 54 kg, it mounts in any orientation -- floor, ceiling, wall or angled -- maximizing layout flexibility. The robot is available in IP40 (standard) and IP67 (wash-down) variants, with a food-grade lubrication option. ABB integrated vision and force control packages streamline integration for picking, insertion and quality inspection tasks.'
    WHEN 'FANUC M-2000iA' THEN 'World strongest 6-axis industrial robot with 2300 kg payload capacity. The 8900 kg M-2000iA reaches 3700 mm and provides 0.1 mm repeatability for automotive body transfer, large casting handling and aerospace fabrication. FANUC integrated intelligent features include force sensing, collision detection and vision-guided motion. The robot is available in multiple variants including a high-reach configuration and a foundry version for heavy manufacturing environments. Proven in automotive assembly plants globally.'
    WHEN 'Digit' THEN 'Bipedal humanoid robot designed for last-mile logistics and warehouse bulk material handling. Digit 16-degree-of-freedom chassis walks and runs at 1.5 m/s while carrying 16 kg loads in its manipulator arms. The 45 kg platform navigates existing warehouse infrastructure -- stairs, ramps, conveyor belts -- without facility modification. Agility Robotics design emphasizes human-scale form factor, enabling Digit to operate in spaces built for people. The platform targets e-commerce fulfillment and parcel handling applications.'
  END
WHERE canonical_name IN ('Atlas','Spot','Stretch','UR5e','UR10e','UR20','KUKA KR 1000 titan','KUKA KR 6 R900','ABB IRB 6700','ABB IRB 1200','FANUC M-2000iA','Digit');
