import { prisma } from '@robotspace/db'
import { CandidateActions } from './candidate-actions'
export const dynamic = 'force-dynamic'
type Candidate = { id: string; candidate_name: string; manufacturer_name: string | null; source_id: string; candidate_url: string; decision_reason: string | null; robot_entity_id: string | null }
export default async function CatalogReviewPage() {
  let candidates: Candidate[] = []
  try { candidates = await prisma.$queryRawUnsafe<Candidate[]>(`SELECT id, candidate_name, manufacturer_name, source_id, candidate_url, decision_reason, robot_entity_id FROM catalog_candidates WHERE status = 'NEEDS_REVIEW' ORDER BY last_seen_at DESC, created_at DESC LIMIT 200`) } catch (error) { console.error('[catalog-review]', error) }
  return <div className="space-y-6"><div><h1 className="text-2xl font-semibold" style={{ color: 'var(--color-text-heading)' }}>Catalog review</h1><p className="mt-1 text-sm" style={{ color: 'var(--color-text-muted)' }}>Accessories, surveys and uncertain catalog items stay here until reviewed. Rejecting preserves the audit trail; restoring is available only for an archived robot entity.</p></div><div className="rounded-xl overflow-hidden border" style={{ borderColor: 'var(--color-border-color)' }}>{candidates.length === 0 ? <p className="p-6 text-sm" style={{ color: 'var(--color-text-muted)' }}>No candidates need review.</p> : <table className="w-full text-sm"><thead><tr style={{ background: 'var(--color-bg-card)' }}><th className="p-3 text-left">Candidate</th><th className="p-3 text-left">Source</th><th className="p-3 text-left">Reason</th><th className="p-3 text-right">Decision</th></tr></thead><tbody>{candidates.map(candidate => <tr key={candidate.id} className="border-t" style={{ borderColor: 'var(--color-border-color)' }}><td className="p-3"><a href={candidate.candidate_url} target="_blank" rel="noreferrer" className="font-medium hover:underline" style={{ color: 'var(--color-text-heading)' }}>{candidate.candidate_name}</a>{candidate.manufacturer_name && <div className="text-xs mt-1" style={{ color: 'var(--color-text-muted)' }}>{candidate.manufacturer_name}</div>}</td><td className="p-3 text-xs" style={{ color: 'var(--color-text-muted)' }}>{candidate.source_id}</td><td className="p-3 text-xs max-w-md" style={{ color: 'var(--color-text-muted)' }}>{candidate.decision_reason || 'Manual review required'}</td><td className="p-3"><CandidateActions id={candidate.id} canRestore={Boolean(candidate.robot_entity_id)} /></td></tr>)}</tbody></table>}</div></div>
}
